//Verilog generated by VPR 8.1.0-dev+9e53e9a0a from post-place-and-route implementation
module dom_mul (
    input \ax ,
    input \ay ,
    input \bx ,
    input \by ,
    input \cx ,
    input \cy ,
    input \z0 ,
    input \z1 ,
    input \z2 ,
    input \clock ,
    input \reset ,
    output \aq ,
    output \bq ,
    output \cq 
);

    //Wires
    wire \ax_output_0_0 ;
    wire \ay_output_0_0 ;
    wire \bx_output_0_0 ;
    wire \by_output_0_0 ;
    wire \cx_output_0_0 ;
    wire \cy_output_0_0 ;
    wire \z0_output_0_0 ;
    wire \z1_output_0_0 ;
    wire \z2_output_0_0 ;
    wire \clock_output_0_0 ;
    wire \reset_output_0_0 ;
    wire \lut_aq_output_0_0 ;
    wire \lut_bq_output_0_0 ;
    wire \lut_cq_output_0_0 ;
    wire \lut_n30_output_0_0 ;
    wire \latch_axay_reg_output_0_0 ;
    wire \lut_n35_output_0_0 ;
    wire \latch_axby_xor_reg_output_0_0 ;
    wire \lut_n40_output_0_0 ;
    wire \latch_axcy_xor_reg_output_0_0 ;
    wire \lut_n45_output_0_0 ;
    wire \latch_bxby_reg_output_0_0 ;
    wire \lut_n50_output_0_0 ;
    wire \latch_bxay_xor_reg_output_0_0 ;
    wire \lut_n55_output_0_0 ;
    wire \latch_bxcy_xor_reg_output_0_0 ;
    wire \lut_n60_output_0_0 ;
    wire \latch_cxcy_reg_output_0_0 ;
    wire \lut_n65_output_0_0 ;
    wire \latch_cxay_xor_reg_output_0_0 ;
    wire \lut_n70_output_0_0 ;
    wire \latch_cxby_xor_reg_output_0_0 ;
    wire \lut_n30_input_0_0 ;
    wire \lut_n40_input_0_3 ;
    wire \lut_n35_input_0_0 ;
    wire \lut_n30_input_0_1 ;
    wire \lut_n50_input_0_2 ;
    wire \lut_n65_input_0_2 ;
    wire \lut_n45_input_0_0 ;
    wire \lut_n55_input_0_2 ;
    wire \lut_n50_input_0_0 ;
    wire \lut_n45_input_0_2 ;
    wire \lut_n35_input_0_3 ;
    wire \lut_n70_input_0_3 ;
    wire \lut_n60_input_0_2 ;
    wire \lut_n65_input_0_1 ;
    wire \lut_n70_input_0_0 ;
    wire \lut_n55_input_0_0 ;
    wire \lut_n40_input_0_2 ;
    wire \lut_n60_input_0_1 ;
    wire \lut_n50_input_0_1 ;
    wire \lut_n35_input_0_1 ;
    wire \lut_n40_input_0_1 ;
    wire \lut_n65_input_0_0 ;
    wire \lut_n55_input_0_3 ;
    wire \lut_n70_input_0_2 ;
    wire \latch_axay_reg_clock_0_0 ;
    wire \latch_bxby_reg_clock_0_0 ;
    wire \latch_bxcy_xor_reg_clock_0_0 ;
    wire \latch_bxay_xor_reg_clock_0_0 ;
    wire \latch_axcy_xor_reg_clock_0_0 ;
    wire \latch_axby_xor_reg_clock_0_0 ;
    wire \latch_cxcy_reg_clock_0_0 ;
    wire \latch_cxay_xor_reg_clock_0_0 ;
    wire \latch_cxby_xor_reg_clock_0_0 ;
    wire \lut_n30_input_0_2 ;
    wire \lut_n45_input_0_1 ;
    wire \lut_n55_input_0_1 ;
    wire \lut_n50_input_0_3 ;
    wire \lut_n40_input_0_0 ;
    wire \lut_n35_input_0_2 ;
    wire \lut_n60_input_0_0 ;
    wire \lut_n65_input_0_3 ;
    wire \lut_n70_input_0_1 ;
    wire \aq_input_0_0 ;
    wire \bq_input_0_0 ;
    wire \cq_input_0_0 ;
    wire \latch_axay_reg_input_0_0 ;
    wire \lut_aq_input_0_0 ;
    wire \latch_axby_xor_reg_input_0_0 ;
    wire \lut_aq_input_0_2 ;
    wire \latch_axcy_xor_reg_input_0_0 ;
    wire \lut_aq_input_0_1 ;
    wire \latch_bxby_reg_input_0_0 ;
    wire \lut_bq_input_0_2 ;
    wire \latch_bxay_xor_reg_input_0_0 ;
    wire \lut_bq_input_0_0 ;
    wire \latch_bxcy_xor_reg_input_0_0 ;
    wire \lut_bq_input_0_1 ;
    wire \latch_cxcy_reg_input_0_0 ;
    wire \lut_cq_input_0_1 ;
    wire \latch_cxay_xor_reg_input_0_0 ;
    wire \lut_cq_input_0_2 ;
    wire \latch_cxby_xor_reg_input_0_0 ;
    wire \lut_cq_input_0_0 ;

    //IO assignments
    assign \aq  = \aq_input_0_0 ;
    assign \bq  = \bq_input_0_0 ;
    assign \cq  = \cq_input_0_0 ;
    assign \ax_output_0_0  = \ax ;
    assign \ay_output_0_0  = \ay ;
    assign \bx_output_0_0  = \bx ;
    assign \by_output_0_0  = \by ;
    assign \cx_output_0_0  = \cx ;
    assign \cy_output_0_0  = \cy ;
    assign \z0_output_0_0  = \z0 ;
    assign \z1_output_0_0  = \z1 ;
    assign \z2_output_0_0  = \z2 ;
    assign \clock_output_0_0  = \clock ;
    assign \reset_output_0_0  = \reset ;

    //Interconnect
    fpga_interconnect \routing_segment_ax_output_0_0_to_lut_n30_input_0_0  (
        .datain(\ax_output_0_0 ),
        .dataout(\lut_n30_input_0_0 )
    );

    fpga_interconnect \routing_segment_ax_output_0_0_to_lut_n40_input_0_3  (
        .datain(\ax_output_0_0 ),
        .dataout(\lut_n40_input_0_3 )
    );

    fpga_interconnect \routing_segment_ax_output_0_0_to_lut_n35_input_0_0  (
        .datain(\ax_output_0_0 ),
        .dataout(\lut_n35_input_0_0 )
    );

    fpga_interconnect \routing_segment_ay_output_0_0_to_lut_n30_input_0_1  (
        .datain(\ay_output_0_0 ),
        .dataout(\lut_n30_input_0_1 )
    );

    fpga_interconnect \routing_segment_ay_output_0_0_to_lut_n50_input_0_2  (
        .datain(\ay_output_0_0 ),
        .dataout(\lut_n50_input_0_2 )
    );

    fpga_interconnect \routing_segment_ay_output_0_0_to_lut_n65_input_0_2  (
        .datain(\ay_output_0_0 ),
        .dataout(\lut_n65_input_0_2 )
    );

    fpga_interconnect \routing_segment_bx_output_0_0_to_lut_n45_input_0_0  (
        .datain(\bx_output_0_0 ),
        .dataout(\lut_n45_input_0_0 )
    );

    fpga_interconnect \routing_segment_bx_output_0_0_to_lut_n55_input_0_2  (
        .datain(\bx_output_0_0 ),
        .dataout(\lut_n55_input_0_2 )
    );

    fpga_interconnect \routing_segment_bx_output_0_0_to_lut_n50_input_0_0  (
        .datain(\bx_output_0_0 ),
        .dataout(\lut_n50_input_0_0 )
    );

    fpga_interconnect \routing_segment_by_output_0_0_to_lut_n45_input_0_2  (
        .datain(\by_output_0_0 ),
        .dataout(\lut_n45_input_0_2 )
    );

    fpga_interconnect \routing_segment_by_output_0_0_to_lut_n35_input_0_3  (
        .datain(\by_output_0_0 ),
        .dataout(\lut_n35_input_0_3 )
    );

    fpga_interconnect \routing_segment_by_output_0_0_to_lut_n70_input_0_3  (
        .datain(\by_output_0_0 ),
        .dataout(\lut_n70_input_0_3 )
    );

    fpga_interconnect \routing_segment_cx_output_0_0_to_lut_n60_input_0_2  (
        .datain(\cx_output_0_0 ),
        .dataout(\lut_n60_input_0_2 )
    );

    fpga_interconnect \routing_segment_cx_output_0_0_to_lut_n65_input_0_1  (
        .datain(\cx_output_0_0 ),
        .dataout(\lut_n65_input_0_1 )
    );

    fpga_interconnect \routing_segment_cx_output_0_0_to_lut_n70_input_0_0  (
        .datain(\cx_output_0_0 ),
        .dataout(\lut_n70_input_0_0 )
    );

    fpga_interconnect \routing_segment_cy_output_0_0_to_lut_n55_input_0_0  (
        .datain(\cy_output_0_0 ),
        .dataout(\lut_n55_input_0_0 )
    );

    fpga_interconnect \routing_segment_cy_output_0_0_to_lut_n40_input_0_2  (
        .datain(\cy_output_0_0 ),
        .dataout(\lut_n40_input_0_2 )
    );

    fpga_interconnect \routing_segment_cy_output_0_0_to_lut_n60_input_0_1  (
        .datain(\cy_output_0_0 ),
        .dataout(\lut_n60_input_0_1 )
    );

    fpga_interconnect \routing_segment_z0_output_0_0_to_lut_n50_input_0_1  (
        .datain(\z0_output_0_0 ),
        .dataout(\lut_n50_input_0_1 )
    );

    fpga_interconnect \routing_segment_z0_output_0_0_to_lut_n35_input_0_1  (
        .datain(\z0_output_0_0 ),
        .dataout(\lut_n35_input_0_1 )
    );

    fpga_interconnect \routing_segment_z1_output_0_0_to_lut_n40_input_0_1  (
        .datain(\z1_output_0_0 ),
        .dataout(\lut_n40_input_0_1 )
    );

    fpga_interconnect \routing_segment_z1_output_0_0_to_lut_n65_input_0_0  (
        .datain(\z1_output_0_0 ),
        .dataout(\lut_n65_input_0_0 )
    );

    fpga_interconnect \routing_segment_z2_output_0_0_to_lut_n55_input_0_3  (
        .datain(\z2_output_0_0 ),
        .dataout(\lut_n55_input_0_3 )
    );

    fpga_interconnect \routing_segment_z2_output_0_0_to_lut_n70_input_0_2  (
        .datain(\z2_output_0_0 ),
        .dataout(\lut_n70_input_0_2 )
    );

    fpga_interconnect \routing_segment_clock_output_0_0_to_latch_axay_reg_clock_0_0  (
        .datain(\clock_output_0_0 ),
        .dataout(\latch_axay_reg_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock_output_0_0_to_latch_bxby_reg_clock_0_0  (
        .datain(\clock_output_0_0 ),
        .dataout(\latch_bxby_reg_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock_output_0_0_to_latch_bxcy_xor_reg_clock_0_0  (
        .datain(\clock_output_0_0 ),
        .dataout(\latch_bxcy_xor_reg_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock_output_0_0_to_latch_bxay_xor_reg_clock_0_0  (
        .datain(\clock_output_0_0 ),
        .dataout(\latch_bxay_xor_reg_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock_output_0_0_to_latch_axcy_xor_reg_clock_0_0  (
        .datain(\clock_output_0_0 ),
        .dataout(\latch_axcy_xor_reg_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock_output_0_0_to_latch_axby_xor_reg_clock_0_0  (
        .datain(\clock_output_0_0 ),
        .dataout(\latch_axby_xor_reg_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock_output_0_0_to_latch_cxcy_reg_clock_0_0  (
        .datain(\clock_output_0_0 ),
        .dataout(\latch_cxcy_reg_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock_output_0_0_to_latch_cxay_xor_reg_clock_0_0  (
        .datain(\clock_output_0_0 ),
        .dataout(\latch_cxay_xor_reg_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock_output_0_0_to_latch_cxby_xor_reg_clock_0_0  (
        .datain(\clock_output_0_0 ),
        .dataout(\latch_cxby_xor_reg_clock_0_0 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_n30_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_n30_input_0_2 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_n45_input_0_1  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_n45_input_0_1 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_n55_input_0_1  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_n55_input_0_1 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_n50_input_0_3  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_n50_input_0_3 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_n40_input_0_0  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_n40_input_0_0 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_n35_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_n35_input_0_2 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_n60_input_0_0  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_n60_input_0_0 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_n65_input_0_3  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_n65_input_0_3 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_n70_input_0_1  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_n70_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_aq_output_0_0_to_aq_input_0_0  (
        .datain(\lut_aq_output_0_0 ),
        .dataout(\aq_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_bq_output_0_0_to_bq_input_0_0  (
        .datain(\lut_bq_output_0_0 ),
        .dataout(\bq_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_cq_output_0_0_to_cq_input_0_0  (
        .datain(\lut_cq_output_0_0 ),
        .dataout(\cq_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n30_output_0_0_to_latch_axay_reg_input_0_0  (
        .datain(\lut_n30_output_0_0 ),
        .dataout(\latch_axay_reg_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_axay_reg_output_0_0_to_lut_aq_input_0_0  (
        .datain(\latch_axay_reg_output_0_0 ),
        .dataout(\lut_aq_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n35_output_0_0_to_latch_axby_xor_reg_input_0_0  (
        .datain(\lut_n35_output_0_0 ),
        .dataout(\latch_axby_xor_reg_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_axby_xor_reg_output_0_0_to_lut_aq_input_0_2  (
        .datain(\latch_axby_xor_reg_output_0_0 ),
        .dataout(\lut_aq_input_0_2 )
    );

    fpga_interconnect \routing_segment_lut_n40_output_0_0_to_latch_axcy_xor_reg_input_0_0  (
        .datain(\lut_n40_output_0_0 ),
        .dataout(\latch_axcy_xor_reg_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_axcy_xor_reg_output_0_0_to_lut_aq_input_0_1  (
        .datain(\latch_axcy_xor_reg_output_0_0 ),
        .dataout(\lut_aq_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_n45_output_0_0_to_latch_bxby_reg_input_0_0  (
        .datain(\lut_n45_output_0_0 ),
        .dataout(\latch_bxby_reg_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_bxby_reg_output_0_0_to_lut_bq_input_0_2  (
        .datain(\latch_bxby_reg_output_0_0 ),
        .dataout(\lut_bq_input_0_2 )
    );

    fpga_interconnect \routing_segment_lut_n50_output_0_0_to_latch_bxay_xor_reg_input_0_0  (
        .datain(\lut_n50_output_0_0 ),
        .dataout(\latch_bxay_xor_reg_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_bxay_xor_reg_output_0_0_to_lut_bq_input_0_0  (
        .datain(\latch_bxay_xor_reg_output_0_0 ),
        .dataout(\lut_bq_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n55_output_0_0_to_latch_bxcy_xor_reg_input_0_0  (
        .datain(\lut_n55_output_0_0 ),
        .dataout(\latch_bxcy_xor_reg_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_bxcy_xor_reg_output_0_0_to_lut_bq_input_0_1  (
        .datain(\latch_bxcy_xor_reg_output_0_0 ),
        .dataout(\lut_bq_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_n60_output_0_0_to_latch_cxcy_reg_input_0_0  (
        .datain(\lut_n60_output_0_0 ),
        .dataout(\latch_cxcy_reg_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_cxcy_reg_output_0_0_to_lut_cq_input_0_1  (
        .datain(\latch_cxcy_reg_output_0_0 ),
        .dataout(\lut_cq_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_n65_output_0_0_to_latch_cxay_xor_reg_input_0_0  (
        .datain(\lut_n65_output_0_0 ),
        .dataout(\latch_cxay_xor_reg_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_cxay_xor_reg_output_0_0_to_lut_cq_input_0_2  (
        .datain(\latch_cxay_xor_reg_output_0_0 ),
        .dataout(\lut_cq_input_0_2 )
    );

    fpga_interconnect \routing_segment_lut_n70_output_0_0_to_latch_cxby_xor_reg_input_0_0  (
        .datain(\lut_n70_output_0_0 ),
        .dataout(\latch_cxby_xor_reg_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_cxby_xor_reg_output_0_0_to_lut_cq_input_0_0  (
        .datain(\latch_cxby_xor_reg_output_0_0 ),
        .dataout(\lut_cq_input_0_0 )
    );


    //Cell instances
    LUT_K #(
        .K(3),
        .LUT_MASK(8'b00001000)
    ) \lut_n30  (
        .in({
            \lut_n30_input_0_2 ,
            \lut_n30_input_0_1 ,
            \lut_n30_input_0_0 
         }),
        .out(\lut_n30_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_axay_reg  (
        .D(\latch_axay_reg_input_0_0 ), 
        .Q(\latch_axay_reg_output_0_0 ), 
        .clock(\latch_axay_reg_clock_0_0 )
    );
    LUT_K #(
        .K(3),
        .LUT_MASK(8'b10010110)
    ) \lut_bq  (
        .in({
            \lut_bq_input_0_2 ,
            \lut_bq_input_0_1 ,
            \lut_bq_input_0_0 
         }),
        .out(\lut_bq_output_0_0 )
    );

    LUT_K #(
        .K(3),
        .LUT_MASK(8'b00100000)
    ) \lut_n45  (
        .in({
            \lut_n45_input_0_2 ,
            \lut_n45_input_0_1 ,
            \lut_n45_input_0_0 
         }),
        .out(\lut_n45_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_bxby_reg  (
        .D(\latch_bxby_reg_input_0_0 ), 
        .Q(\latch_bxby_reg_output_0_0 ), 
        .clock(\latch_bxby_reg_clock_0_0 )
    );
    LUT_K #(
        .K(4),
        .LUT_MASK(16'b0001001100100000)
    ) \lut_n55  (
        .in({
            \lut_n55_input_0_3 ,
            \lut_n55_input_0_2 ,
            \lut_n55_input_0_1 ,
            \lut_n55_input_0_0 
         }),
        .out(\lut_n55_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_bxcy_xor_reg  (
        .D(\latch_bxcy_xor_reg_input_0_0 ), 
        .Q(\latch_bxcy_xor_reg_output_0_0 ), 
        .clock(\latch_bxcy_xor_reg_clock_0_0 )
    );
    LUT_K #(
        .K(4),
        .LUT_MASK(16'b0000000001101100)
    ) \lut_n50  (
        .in({
            \lut_n50_input_0_3 ,
            \lut_n50_input_0_2 ,
            \lut_n50_input_0_1 ,
            \lut_n50_input_0_0 
         }),
        .out(\lut_n50_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_bxay_xor_reg  (
        .D(\latch_bxay_xor_reg_input_0_0 ), 
        .Q(\latch_bxay_xor_reg_output_0_0 ), 
        .clock(\latch_bxay_xor_reg_clock_0_0 )
    );
    LUT_K #(
        .K(4),
        .LUT_MASK(16'b0001010001000100)
    ) \lut_n40  (
        .in({
            \lut_n40_input_0_3 ,
            \lut_n40_input_0_2 ,
            \lut_n40_input_0_1 ,
            \lut_n40_input_0_0 
         }),
        .out(\lut_n40_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_axcy_xor_reg  (
        .D(\latch_axcy_xor_reg_input_0_0 ), 
        .Q(\latch_axcy_xor_reg_output_0_0 ), 
        .clock(\latch_axcy_xor_reg_clock_0_0 )
    );
    LUT_K #(
        .K(3),
        .LUT_MASK(8'b10010110)
    ) \lut_aq  (
        .in({
            \lut_aq_input_0_2 ,
            \lut_aq_input_0_1 ,
            \lut_aq_input_0_0 
         }),
        .out(\lut_aq_output_0_0 )
    );

    LUT_K #(
        .K(4),
        .LUT_MASK(16'b0000011000001100)
    ) \lut_n35  (
        .in({
            \lut_n35_input_0_3 ,
            \lut_n35_input_0_2 ,
            \lut_n35_input_0_1 ,
            \lut_n35_input_0_0 
         }),
        .out(\lut_n35_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_axby_xor_reg  (
        .D(\latch_axby_xor_reg_input_0_0 ), 
        .Q(\latch_axby_xor_reg_output_0_0 ), 
        .clock(\latch_axby_xor_reg_clock_0_0 )
    );
    LUT_K #(
        .K(3),
        .LUT_MASK(8'b01000000)
    ) \lut_n60  (
        .in({
            \lut_n60_input_0_2 ,
            \lut_n60_input_0_1 ,
            \lut_n60_input_0_0 
         }),
        .out(\lut_n60_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_cxcy_reg  (
        .D(\latch_cxcy_reg_input_0_0 ), 
        .Q(\latch_cxcy_reg_output_0_0 ), 
        .clock(\latch_cxcy_reg_clock_0_0 )
    );
    LUT_K #(
        .K(3),
        .LUT_MASK(8'b10010110)
    ) \lut_cq  (
        .in({
            \lut_cq_input_0_2 ,
            \lut_cq_input_0_1 ,
            \lut_cq_input_0_0 
         }),
        .out(\lut_cq_output_0_0 )
    );

    LUT_K #(
        .K(4),
        .LUT_MASK(16'b0000000001101010)
    ) \lut_n65  (
        .in({
            \lut_n65_input_0_3 ,
            \lut_n65_input_0_2 ,
            \lut_n65_input_0_1 ,
            \lut_n65_input_0_0 
         }),
        .out(\lut_n65_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_cxay_xor_reg  (
        .D(\latch_cxay_xor_reg_input_0_0 ), 
        .Q(\latch_cxay_xor_reg_output_0_0 ), 
        .clock(\latch_cxay_xor_reg_clock_0_0 )
    );
    LUT_K #(
        .K(4),
        .LUT_MASK(16'b0001001000110000)
    ) \lut_n70  (
        .in({
            \lut_n70_input_0_3 ,
            \lut_n70_input_0_2 ,
            \lut_n70_input_0_1 ,
            \lut_n70_input_0_0 
         }),
        .out(\lut_n70_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_cxby_xor_reg  (
        .D(\latch_cxby_xor_reg_input_0_0 ), 
        .Q(\latch_cxby_xor_reg_output_0_0 ), 
        .clock(\latch_cxby_xor_reg_clock_0_0 )
    );

endmodule
