/* Generated by Yosys 0.27+3 (git sha1 b58664d44, gcc 11.3.0-1ubuntu1~22.04 -fPIC -Os) */

module maskmul(\am[0] , \am[1] , \bm[0] , \bm[1] , \ma[0] , \ma[1] , \mb[0] , \mb[1] , \mq[0] , \mq[1] , reset, clk, \qm[0] , \qm[1] );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  input \am[0] ;
  wire \am[0] ;
  input \am[1] ;
  wire \am[1] ;
  input \bm[0] ;
  wire \bm[0] ;
  input \bm[1] ;
  wire \bm[1] ;
  input clk;
  wire clk;
  input \ma[0] ;
  wire \ma[0] ;
  input \ma[1] ;
  wire \ma[1] ;
  input \mb[0] ;
  wire \mb[0] ;
  input \mb[1] ;
  wire \mb[1] ;
  input \mq[0] ;
  wire \mq[0] ;
  input \mq[1] ;
  wire \mq[1] ;
  wire n30;
  wire n34;
  output \qm[0] ;
  reg \qm[0] ;
  output \qm[1] ;
  reg \qm[1] ;
  input reset;
  wire reset;
  always @(posedge clk)
    \qm[0]  <= n30;
  always @(posedge clk)
    \qm[1]  <= n34;
  assign n34 = 8'h14 >> { _04_, _05_, reset };
  assign _00_ = 16'h1428 >> { \am[1] , \bm[1] , \mb[1] , \ma[1]  };
  assign _01_ = 16'h1428 >> { \bm[0] , \am[0] , \ma[0] , \mb[0]  };
  assign n30 = 16'h4114 >> { _00_, _01_, \mq[0] , reset };
  assign _02_ = 4'h6 >> { \bm[0] , \mb[0]  };
  assign _03_ = 4'h6 >> { \bm[1] , \mb[1]  };
  assign _04_ = 16'h1428 >> { \am[1] , _02_, _03_, \ma[1]  };
  assign _05_ = 16'hd728 >> { \mq[1] , \am[0] , \ma[0] , _03_ };
endmodule
